{
 "title": "FoundationDB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(fdb_database_available, job)"
   },
   {
    "name": "machines",
    "query": "label_values(fdb_process_uptime_seconds, address)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database is Available",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fdb_database_available{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Database is Locked",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fdb_database_locked{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "fdb_clients_total{job=\"$job\"}"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(fdb_workload_operations_read_requests_total{job=\"$job\"}[5m])",
     "legendFormat": "Read requests"
    },
    {
     "expr": "rate(fdb_workload_operations_reads_total{job=\"$job\"}[5m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(fdb_workload_operations_writes_total{job=\"$job\"}[5m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(fdb_workload_transactions_started_total{job=\"$job\"}[5m])",
     "legendFormat": "Transactions started"
    },
    {
     "expr": "rate(fdb_workload_transactions_committed_total{job=\"$job\"}[5m])",
     "legendFormat": "Transactions committed"
    }
   ]
  },
  {
   "title": "Transaction Conflicts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fdb_workload_transactions_conflicted_total{job=\"$job\"}[5m])",
     "legendFormat": "Transactions conflicted"
    }
   ]
  },
  {
   "title": "Keys Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(fdb_workload_keys_read_total{job=\"$job\"}[5m])",
     "legendFormat": "Keys read"
    }
   ]
  },
  {
   "title": "Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(fdb_workload_bytes_read_total{job=\"$job\"}[5m])",
     "legendFormat": "Bytes read"
    },
    {
     "expr": "rate(fdb_workload_bytes_written_total{job=\"$job\"}[5m])",
     "legendFormat": "Bytes written"
    }
   ]
  },
  { "title": "Latency Probe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fdb_latency_probe_read_seconds{job=\"$job\"}",
     "legendFormat": "Time to perform a single read"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fdb_latency_probe_commit_seconds{job=\"$job\"}",
     "legendFormat": "Time to commit a sample transaction"
    }
   ]
  },
  {
   "title": "Transaction Start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fdb_latency_probe_transaction_start_seconds{job=\"$job\"}",
     "legendFormat": "Time to start a sample transaction at normal priority"
    }
   ]
  },
  {
   "title": "Immediate Priority Transaction Start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fdb_latency_probe_immediate_priority_transaction_start_seconds{job=\"$job\"}",
     "legendFormat": "Time to start a sample transaction at system immediate priority"
    }
   ]
  },
  {
   "title": "Batch Priority Transaction Start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fdb_latency_probe_batch_priority_transaction_start_seconds{job=\"$job\"}",
     "legendFormat": "Time to start a sample transaction at batch priority"
    }
   ]
  },
  { "title": "Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Machine $machines",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "repeat": "machines",
   "targets": [
    {
     "expr": "sum(fdb_process_cpu_usage_cores{job=\"$job\", address=~\"($machines):\\\\d+\"}) by (address)"
    },
    {
     "expr": "sum(fdb_process_memory_used_bytes{job=\"$job\", address=~\"($machines):\\\\d+\"}) by (address)"
    },
    {
     "expr": "sum(fdb_process_memory_used_bytes{job=\"$job\", address=~\"($machines):\\\\d+\"} / fdb_process_memory_limit_bytes) by (address)"
    },
    {
     "expr": "sum(rate(fdb_process_disk_reads_total{job=\"$job\", address=~\"($machines):\\\\d+\"} + fdb_process_disk_writes_total)) by (address)"
    },
    {
     "expr": "sum(1.0 - fdb_process_disk_free_bytes{job=\"$job\", address=~\"($machines):\\\\d+\"} / fdb_process_disk_total_bytes) by (address)"
    },
    {
     "expr": "sum(fdb_process_disk_usage_ratio{job=\"$job\", address=~\"($machines):\\\\d+\"}) by (address)"
    },
    {
     "expr": "sum(fdb_process_network_megabits_received_rate{job=\"$job\", address=~\"($machines):\\\\d+\"} + fdb_process_network_megabits_sent_rate) by (address)"
    },
    {
     "expr": "sum(fdb_process_network_current_connections_total{job=\"$job\", address=~\"($machines):\\\\d+\"}) by (address)"
    },
    {
     "expr": "sum(fdb_process_role{job=\"$job\", address=~\"($machines):\\\\d+\"}) by (address, role)"
    }
   ]
  }
 ]
}